// This Automator file is automatically
// created.
// It this is a test,
// this file (and related reference images)
// can be copied in the /src/tests folder
// to make them available in the testing
// environment.
var SystemTest_menuMorphShadowIsCorrectWhileAndAfterDragging_automationCommands;

SystemTest_menuMorphShadowIsCorrectWhileAndAfterDragging_automationCommands = {
    "automatorCommandsSequence": [
        {
            "mouseX": 818,
            "mouseY": 256,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 10,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 813,
            "mouseY": 256,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 605,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 790,
            "mouseY": 259,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 757,
            "mouseY": 265,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 693,
            "mouseY": 278,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 588,
            "mouseY": 304,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 507,
            "mouseY": 331,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 418,
            "mouseY": 365,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 371,
            "mouseY": 383,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 344,
            "mouseY": 393,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 340,
            "mouseY": 394,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 338,
            "mouseY": 397,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 182,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 334,
            "mouseY": 402,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 329,
            "mouseY": 405,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 326,
            "mouseY": 407,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 321,
            "mouseY": 408,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 315,
            "mouseY": 410,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 308,
            "mouseY": 413,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 300,
            "mouseY": 415,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 294,
            "mouseY": 418,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 290,
            "mouseY": 420,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 286,
            "mouseY": 422,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 281,
            "mouseY": 424,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 279,
            "mouseY": 425,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 276,
            "mouseY": 426,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 275,
            "mouseY": 427,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 273,
            "mouseY": 427,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 272,
            "mouseY": 428,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 271,
            "mouseY": 428,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 270,
            "mouseY": 429,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 268,
            "mouseY": 429,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 268,
            "mouseY": 430,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 267,
            "mouseY": 431,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 266,
            "mouseY": 432,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 265,
            "mouseY": 433,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 264,
            "mouseY": 434,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 263,
            "mouseY": 435,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 262,
            "mouseY": 436,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 262,
            "mouseY": 437,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "millisecondsSincePreviousCommand": 462,
            "automatorCommandName": "AutomatorCommandTurnOffAnimationsPacingControl"
        },
        {
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandTurnOffAlignmentOfMorphIDsMechanism"
        },
        {
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandTurnOffHidingOfMorphsGeometryInfoInLabels"
        },
        {
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandTurnOffHidingOfMorphsContentExtractInLabels"
        },
        {
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandTurnOffHidingOfMorphsNumberIDInLabels"
        },
        {
            "millisecondsSincePreviousCommand": 459,
            "automatorCommandName": "AutomatorCommandResetWorld"
        },
        {
            "millisecondsSincePreviousCommand": 1102,
            "automatorCommandName": "AutomatorCommandTurnOnAnimationsPacingControl"
        },
        {
            "millisecondsSincePreviousCommand": 881,
            "automatorCommandName": "AutomatorCommandTurnOnAlignmentOfMorphIDsMechanism"
        },
        {
            "millisecondsSincePreviousCommand": 713,
            "automatorCommandName": "AutomatorCommandTurnOnHidingOfMorphsGeometryInfoInLabels"
        },
        {
            "millisecondsSincePreviousCommand": 715,
            "automatorCommandName": "AutomatorCommandTurnOnHidingOfMorphsContentExtractInLabels"
        },
        {
            "millisecondsSincePreviousCommand": 757,
            "automatorCommandName": "AutomatorCommandTurnOnHidingOfMorphsNumberIDInLabels"
        },
        {
            "mouseX": 262,
            "mouseY": 390,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 298,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 236,
            "mouseY": 316,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 224,
            "mouseY": 264,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 218,
            "mouseY": 232,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 215,
            "mouseY": 216,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 214,
            "mouseY": 204,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 214,
            "mouseY": 202,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 211,
            "mouseY": 199,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 171,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 200,
            "mouseY": 189,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 189,
            "mouseY": 176,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 175,
            "mouseY": 162,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 153,
            "mouseY": 134,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 138,
            "mouseY": 113,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 124,
            "mouseY": 90,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 114,
            "mouseY": 74,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 111,
            "mouseY": 66,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 107,
            "mouseY": 59,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 104,
            "mouseY": 55,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 103,
            "mouseY": 52,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 102,
            "mouseY": 50,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 101,
            "mouseY": 47,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 100,
            "mouseY": 46,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 98,
            "mouseY": 44,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 95,
            "mouseY": 43,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 92,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 89,
            "mouseY": 39,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 86,
            "mouseY": 37,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 84,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 83,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 82,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 81,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 22,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "upOrDown": "down",
            "buttons": 2,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "morphUniqueIDString": "WorldMorph#1",
            "morphPathRelativeToWorld": {
                "actualPath": [],
                "lengthOfChildrenArrays": []
            },
            "morphIdentifierViaTextLabel": [
                "WorldMorph (class name)",
                0,
                1
            ],
            "absoluteBoundsOfMorphRelativeToWorld": [
                0,
                0,
                960,
                440
            ],
            "pointerPositionFractionalInMorph": [
                0.084375,
                0.08181818181818182
            ],
            "pointerPositionPixelsInMorph": [
                81,
                36
            ],
            "pointerPositionPixelsInWorld": {
                "x": 81,
                "y": 36
            },
            "isPartOfListMorph": false,
            "millisecondsSincePreviousCommand": 649,
            "button": "right",
            "automatorCommandName": "AutomatorCommandMouseButtonChange"
        },
        {
            "upOrDown": "up",
            "buttons": false,
            "ctrlKey": 0,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "morphUniqueIDString": "WorldMorph#1",
            "morphPathRelativeToWorld": {
                "actualPath": [],
                "lengthOfChildrenArrays": []
            },
            "morphIdentifierViaTextLabel": [
                "WorldMorph (class name)",
                0,
                1
            ],
            "absoluteBoundsOfMorphRelativeToWorld": [
                0,
                0,
                960,
                440
            ],
            "pointerPositionFractionalInMorph": [
                0.084375,
                0.08181818181818182
            ],
            "pointerPositionPixelsInMorph": [
                81,
                36
            ],
            "pointerPositionPixelsInWorld": {
                "x": 81,
                "y": 36
            },
            "isPartOfListMorph": false,
            "millisecondsSincePreviousCommand": 7,
            "button": "right",
            "automatorCommandName": "AutomatorCommandMouseButtonChange"
        },
        {
            "morphToOpenContextMenuAgainst_UniqueIDString": "WorldMorph#1",
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandOpenContextMenu"
        },
        {
            "ctrlKey": null,
            "morphUniqueIDString": "WorldMorph#1",
            "morphPathRelativeToWorld": {
                "actualPath": [],
                "lengthOfChildrenArrays": []
            },
            "morphIdentifierViaTextLabel": [
                "WorldMorph (class name)",
                0,
                1
            ],
            "absoluteBoundsOfMorphRelativeToWorld": [
                0,
                0,
                960,
                440
            ],
            "pointerPositionFractionalInMorph": [
                0.084375,
                0.08181818181818182
            ],
            "pointerPositionPixelsInMorph": [
                81,
                36
            ],
            "pointerPositionPixelsInWorld": {
                "x": 81,
                "y": 36
            },
            "isPartOfListMorph": false,
            "millisecondsSincePreviousCommand": 0,
            "button": "right",
            "automatorCommandName": "AutomatorCommandMouseClick"
        },
        {
            "mouseX": 82,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 750,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 83,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 33,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 84,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 36,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 85,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 13,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 87,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 21,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 88,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 23,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 90,
            "mouseY": 36,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 91,
            "mouseY": 37,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 10,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 92,
            "mouseY": 37,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 13,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 93,
            "mouseY": 37,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 94,
            "mouseY": 37,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 94,
            "mouseY": 38,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 95,
            "mouseY": 38,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 95,
            "mouseY": 39,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 31,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 96,
            "mouseY": 39,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 96,
            "mouseY": 40,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 97,
            "mouseY": 40,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 22,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 97,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 733,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 584,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "screenShotImageName": "SystemTest_menuMorphShadowIsCorrectWhileAndAfterDragging_image_1",
            "screenshotTakenOfAParticularMorph": false,
            "millisecondsSincePreviousCommand": 1,
            "automatorCommandName": "AutomatorCommandScreenshot"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 107,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 88,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "mouseX": 98,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 790,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 99,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 101,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 102,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 103,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 20,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 104,
            "mouseY": 41,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 104,
            "mouseY": 42,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 113,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 103,
            "mouseY": 42,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 195,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 103,
            "mouseY": 43,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 102,
            "mouseY": 43,
            "floatDraggingSomething": false,
            "button": 0,
            "buttons": 0,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 33,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "upOrDown": "down",
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "morphUniqueIDString": "BoxMorph#1001",
            "morphPathRelativeToWorld": {
                "actualPath": [
                    0,
                    1
                ],
                "lengthOfChildrenArrays": [
                    1,
                    19
                ]
            },
            "morphIdentifierViaTextLabel": [
                "BoxMorph (class name)",
                0,
                1
            ],
            "absoluteBoundsOfMorphRelativeToWorld": [
                83,
                38,
                133,
                17
            ],
            "pointerPositionFractionalInMorph": [
                0.14285714285714285,
                0.29411764705882354
            ],
            "pointerPositionPixelsInMorph": [
                19,
                5
            ],
            "pointerPositionPixelsInWorld": {
                "x": 102,
                "y": 43
            },
            "isPartOfListMorph": false,
            "millisecondsSincePreviousCommand": 376,
            "button": "left",
            "automatorCommandName": "AutomatorCommandMouseButtonChange"
        },
        {
            "millisecondsSincePreviousCommand": 479,
            "automatorCommandName": "AutomatorCommandGrab"
        },
        {
            "mouseX": 103,
            "mouseY": 43,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 7,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 106,
            "mouseY": 44,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 27,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 108,
            "mouseY": 44,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 25,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 110,
            "mouseY": 45,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 13,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 113,
            "mouseY": 46,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 21,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 115,
            "mouseY": 47,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 116,
            "mouseY": 48,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 13,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 118,
            "mouseY": 48,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 119,
            "mouseY": 49,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 120,
            "mouseY": 50,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 122,
            "mouseY": 50,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 122,
            "mouseY": 51,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 123,
            "mouseY": 51,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 124,
            "mouseY": 51,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 124,
            "mouseY": 52,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 26,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 125,
            "mouseY": 52,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 24,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 126,
            "mouseY": 52,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 126,
            "mouseY": 53,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 74,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 789,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 272,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "screenShotImageName": "SystemTest_menuMorphShadowIsCorrectWhileAndAfterDragging_image_2",
            "screenshotTakenOfAParticularMorph": false,
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandScreenshot"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 44,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 159,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "mouseX": 128,
            "mouseY": 53,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 1358,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 131,
            "mouseY": 53,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 134,
            "mouseY": 55,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 139,
            "mouseY": 56,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 142,
            "mouseY": 58,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 144,
            "mouseY": 58,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 145,
            "mouseY": 59,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 27,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 146,
            "mouseY": 60,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 147,
            "mouseY": 60,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 148,
            "mouseY": 61,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 149,
            "mouseY": 62,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 150,
            "mouseY": 62,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 152,
            "mouseY": 63,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 15,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 153,
            "mouseY": 64,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 19,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 154,
            "mouseY": 64,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 156,
            "mouseY": 65,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 158,
            "mouseY": 66,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 17,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 159,
            "mouseY": 67,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 18,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 161,
            "mouseY": 68,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 163,
            "mouseY": 68,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 16,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 163,
            "mouseY": 69,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 20,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 164,
            "mouseY": 69,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 14,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "mouseX": 164,
            "mouseY": 70,
            "floatDraggingSomething": true,
            "button": 0,
            "buttons": 1,
            "ctrlKey": false,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 162,
            "automatorCommandName": "AutomatorCommandMouseMove"
        },
        {
            "upOrDown": "up",
            "buttons": false,
            "ctrlKey": 0,
            "shiftKey": false,
            "altKey": false,
            "metaKey": false,
            "morphUniqueIDString": "WorldMorph#1",
            "morphPathRelativeToWorld": {
                "actualPath": [],
                "lengthOfChildrenArrays": []
            },
            "morphIdentifierViaTextLabel": [
                "WorldMorph (class name)",
                0,
                1
            ],
            "absoluteBoundsOfMorphRelativeToWorld": [
                0,
                0,
                960,
                440
            ],
            "pointerPositionFractionalInMorph": [
                0.17083333333333334,
                0.1590909090909091
            ],
            "pointerPositionPixelsInMorph": [
                164,
                70
            ],
            "pointerPositionPixelsInWorld": {
                "x": 164,
                "y": 70
            },
            "isPartOfListMorph": false,
            "millisecondsSincePreviousCommand": 730,
            "button": "left",
            "automatorCommandName": "AutomatorCommandMouseButtonChange"
        },
        {
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandDrop"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 568,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 424,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "screenShotImageName": "SystemTest_menuMorphShadowIsCorrectWhileAndAfterDragging_image_3",
            "screenshotTakenOfAParticularMorph": false,
            "millisecondsSincePreviousCommand": 0,
            "automatorCommandName": "AutomatorCommandScreenshot"
        },
        {
            "scanCode": 67,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 107,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": false,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 209,
            "automatorCommandName": "AutomatorCommandKeyUp"
        },
        {
            "scanCode": 18,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 319,
            "automatorCommandName": "AutomatorCommandKeyDown"
        },
        {
            "scanCode": 84,
            "shiftKey": false,
            "ctrlKey": false,
            "altKey": true,
            "metaKey": false,
            "millisecondsSincePreviousCommand": 585,
            "automatorCommandName": "AutomatorCommandKeyDown"
        }
    ]
};