// Generated by CoffeeScript 1.7.1
window.FittingSpecTextInSmallerBounds_coffeSource = '# FittingSpecTextInSmallerBounds\n\n\nclass FittingSpecTextInSmallerBounds\n  @CROP: true\n  @SCALEDOWN: false\n';
